# Generated by Django 5.2.4 on 2025-07-25 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Guruh nomi...', max_length=150),
            preserve_default=False,
        ),
    ]
