# Generated by Django 5.2.4 on 2025-07-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='Guruh nomi...', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(related_name='students', to='students.group'),
        ),
    ]
